name: flutter_volc_engine_tt_example
description: "Demonstrates how to use the flutter_volc_engine_tt plugin."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_volc_engine_tt:
    path: ../

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
