name: flutter_volc_engine_tt
description: "The Flutter plugin providers volcengine tt sdk native APIs to implement video player. 集成火山云视频点播原生SDK。"
version: 0.0.1
homepage: https://github.com/LiWenHui96
repository: https://github.com/LiWenHui96/VolcEngine_TT_Flutter_SDK
issue_tracker: https://github.com/LiWenHui96/VolcEngine_TT_Flutter_SDK/issues
topics:
  - 火山云
  - TTSDK
  - video

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.volcengine.ttsdk.flutter
        pluginClass: FlutterVolcEngineTTPlugin
      ios:
        pluginClass: FlutterVolcEngineTTPlugin
